// Generated by CoffeeScript 1.12.7
(function() {
  var Descriptor, LayerInfo, VectorOrigination,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  LayerInfo = require('../layer_info.js');

  Descriptor = require('../descriptor.js');

  module.exports = VectorOrigination = (function(superClass) {
    extend(VectorOrigination, superClass);

    function VectorOrigination() {
      return VectorOrigination.__super__.constructor.apply(this, arguments);
    }

    VectorOrigination.shouldParse = function(key) {
      return key === 'vogk';
    };

    VectorOrigination.prototype.parse = function() {
      this.file.seek(8, true);
      if (this.layer.name === '矩形 28 副本 13 拷贝 2') {
        console.log();
      }
      this.data = new Descriptor(this.file).parse();
      return
    };

    return VectorOrigination;

  })(LayerInfo);

}).call(this);
