// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    Greyscale: require('./image_modes/greyscale.js'),
    RGB: require('./image_modes/rgb.js'),
    CMYK: require('./image_modes/cmyk.js')
  };

}).call(this);
